version: '3'

volumes:
  postgres_data: {}
  postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: {{cookiecutter.repository_name}}_django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local
    ports:
      - "8000:8000"
      - "5678:5678"
    command: /start_local

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: {{cookiecutter.repository_name}}_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.envs/.local

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
