version: '3'

services:
  django:
    image: piedpiper-api_production:latest
    env_file:
      - ./.envs/.production
    command: /start
    networks:
      - net
      - traefik-public
    deploy:
      labels:
        - traefik.frontend.rule=Host:piedpiper.com
        - traefik.enable=true
        - traefik.port=5000
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https

networks:
  net:
    driver: overlay
  traefik-public:
    external: true
